extend-exclude = []
line-length = 88
target-version = "py311"
lint.ignore = [
  "B905", # zip-without-explicit-strict
  "C901", # complex-structure
  "D100", # undocumented-public-module
  "D104", # undocumented-public-nested-class
  "D203", # incorrect-blank-line-before-class
  "D213", # multi-line-summary-second-line
  "D400", # missing-trailing-period
  "D401", # non-imperative-mood
  "E722", # bare-except
  "F401", # unused-import
  "FBT002", # boolean-default-value-positional-argument
  "FBT003", # boolean-positional-value-in-call
  "FIX", # line-contains-fixme
  "PERF401", # manual-list-comprehension
  "PLC0206", # dict-index-missing-items (
  "PLC0415", # import-outside-top-level (
  "PLR0913", # too-many-arguments
  "PLR2004", # magic-value-comparison
  "PTH109", # os-getcwd
  "PTH123", # py-path
  "PTH208", # os-listdir
  "RET503", # implicit-return
  "RUF005", # collection-literal-concatenation
  "S101", # assert
  "S311", # suspicious-non-cryptographic-random-usage
  "S314", # suspicious-telnet-usage
  "S605", # start-process-with-a-shell (
  "SIM105", # suppressible-exception
  "SIM115", # open-file-with-context-handler
  "TID252", # relative-imports
  "TRY300", # try-consider-else
]
lint.select = [
  "A", # flake8-builtins
  "ARG", # flake8-unused-arguments
  "B", # flake8-bugbear
  "BLE", # flake8-blind-except
  "C",
  "C4", # flake8-comprehensions
  "C90", # mccabe
  "D", # pydocstyle
  "DTZ", # flake8-datetimez
  "E", # pycodestyle errors
  "EM", # flake8-errmsg
  "EXE", # flake8-executable
  "F",
  "FBT", # flake8-boolean-trap
  "FIX", # flake8-fixme
  "FLY", # flynt
  "G", # flake8-logging-format
  "I", # isort
  "ICN", # flake8-import-conventions
  "N", # PEP8 naming
  "PERF", # perflint
  "PIE", # flake8-pie
  "PL", # pylint
  "PT", # flake8-pytest-style
  "PTH", # flake8-use-pathlib
  "Q", # flake8-quotes
  "RET", # flake8-return
  "RSE", # flake8-raise
  "RUF", # Ruff rules
  "S", # flake8-bandit
  "SIM", # flake8-simplify
  "SLF", # flake8-self
  "SLOT", # flake8-slots
  "T10", # flake8-debugger
  "TCH", # flake8-type-checking
  "TID", # flake8-tidy-imports
  "TRY", # tryceratops
  "UP", # pyupgrade
  "W", # pycodestyle warnings
  "YTT"
  # flake8-2020
]

[lint.flake8-builtins]
builtins-ignorelist = ["id"]

[lint.mccabe]
max-complexity = 10
